### PR TITLE
Update to Sdk 3.38

### LINKED ISSUE #2: Update runtime to 3.38

### PR DESCRIPTION
**Pull request by filipestevao**
Resolves #2

### CODE REVIEW

**Comment by filipestevao** [comment]
bot, build

**Comment by filipestevao** [comment]
bot, build

**Comment by filipestevao** [comment]
bot, build

**Comment by filipestevao** [comment]
Despite having builded successfully, the "tag" was removed, making the last upstream commit to be used. I don't think it's a good practice, but I haven't found another solution.

Highlighting that the last upstream commit was in Oct/2019 and that this build error has already been reported [here](https://github.com/midori-browser/core/issues/427).

I leave it open for other solutions or for the merge, if that is the need.

**Comment by bbhtt** [comment]
Thank you for your work. However 3.38 is EOL now, so I made and merged a PR to update it to the latest GNOME platform 42. That should solve the original issue.

Thanks!

**Pull request closed without merging**
