### PR TITLE
Update

### PR DESCRIPTION
**Pull request by bbhtt**
Fixes https://github.com/flathub/org.midori_browser.Midori/pull/3

Supersedes https://github.com/flathub/org.midori_browser.Midori/pull/3

Midori has moved to a new parent company and a new browser using Electron under the same name https://gitlab.com/midori-web/midori-desktop. The domain having the screenshot is down and I couldn't find any official screenshots of the old one.

### CODE REVIEW

**Comment by bbhtt** [comment]
Ping @m4u9 if you have time, please review. Thanks!

**Comment by m4u9** [comment]
@bbhtt are you interested in taking over maintaining this? I no longer use midori

**Comment by bbhtt** [comment]
> @bbhtt are you interested in taking over maintaining this? I no longer use midori

Sure, that'd be nice. Thank you!

**Comment by m4u9** [comment]
Great! Do you know how to do this? I cannot find any settings nor documentation about it.

**Comment by bbhtt** [comment]
> Great! Do you know how to do this? I cannot find any settings nor documentation about it.

You'd have to ask one of the org members to send me an invite. You can make an issue in https://github.com/flathub/flathub/issues

**Comment by bbhtt** [comment]
I got access after requesting it in #flatpak:matrix.org. Merging now.

**Pull request merged**
